# This is a basic workflow to help you get started with Actions

name: Deploy packages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ build ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Build hhnl.HomeAssistantNet.Automations.csproj
        run: dotnet build ./c_sharp_for_home_assistant/src/hhnl.HomeAssistantNet/hhnl.HomeAssistantNet.Automations/hhnl.HomeAssistantNet.Automations.csproj -c Release
      
      - name: Build hhnl.HomeAssistantNet.Shared.csproj
        run: dotnet build ./c_sharp_for_home_assistant/src/hhnl.HomeAssistantNet/hhnl.HomeAssistantNet.Shared/hhnl.HomeAssistantNet.Shared.csproj -c Release
      
      - name: Build hhnl.HomeAssistantNet.Generator.csproj
        run: dotnet build ./c_sharp_for_home_assistant/src/hhnl.HomeAssistantNet/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.csproj -c Release
      
      - name: Pack hhnl.HomeAssistantNet.Automations.csproj
        run: dotnet pack ./c_sharp_for_home_assistant/src/hhnl.HomeAssistantNet/hhnl.HomeAssistantNet.Automations/hhnl.HomeAssistantNet.Automations.csproj -c Release -o .
      
      - name: Pack hhnl.HomeAssistantNet.Shared.csproj
        run: dotnet pack ./c_sharp_for_home_assistant/src/hhnl.HomeAssistantNet/hhnl.HomeAssistantNet.Shared/hhnl.HomeAssistantNet.Shared.csproj -c Release -o .
      
      - name: Pack hhnl.HomeAssistantNet.Generator.csproj
        run: dotnet pack ./c_sharp_for_home_assistant/src/hhnl.HomeAssistantNet/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.csproj -c Release -o .
        
      - name: Push
        run: dotnet nuget push "*.nupkg" --source nuget.org --skip-duplicate --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
